# Generated by Django 5.2.16 on 2026-07-29 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='Taille en octets')),
                ('mime_type', models.CharField(max_length=100)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.FloatField(blank=True, help_text='Durée en secondes', null=True)),
                ('sample_rate', models.IntegerField(blank=True, null=True)),
                ('bitrate', models.IntegerField(blank=True, null=True)),
                ('channels', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'audio',
                'ordering': ['-uploaded_at'],
                'abstract': False,
            },
        ),
    ]
