services:
  db:
    profiles:
      - disabled

  minio:
    profiles:
      - disabled

  redis:
    profiles:
      - disabled

  backend:
    image: ghcr.io/tawounfouet/clickmart-backend:latest
    env_file:
      - ./backend/.envs/.prod

  celery-worker:
    image: ghcr.io/tawounfouet/clickmart-backend:latest
    env_file:
      - ./backend/.envs/.prod

  celery-beat:
    image: ghcr.io/tawounfouet/clickmart-backend:latest
    env_file:
      - ./backend/.envs/.prod

  frontend:
    image: ghcr.io/tawounfouet/clickmart-frontend:latest

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./infra/certbot/www:/var/www/certbot
      - ./infra/certbot/conf:/etc/letsencrypt
      - ./backend/uploads:/uploads
      - ./backend/static:/static:ro

  certbot:
    image: certbot/certbot
    volumes:
      - ./infra/certbot/www:/var/www/certbot
      - ./infra/certbot/conf:/etc/letsencrypt
      - ./infra/scripts/certbot-deploy-hook.sh:/usr/local/bin/deploy-hook.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --quiet --deploy-hook /usr/local/bin/deploy-hook.sh; sleep 12h; done'"
    restart: unless-stopped
    depends_on:
      - nginx
    mem_limit: 32m

volumes:
  postgres_data:
    name: clickmart_postgres_data
