# Generated by Django 5.2.15 on 2026-07-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cartitem_cart'),
        ('products', '0002_product_tax_percent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
