# Generated by Django 5.2.15 on 2026-07-30 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_add_unique_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
