# Generated by Django 5.2.16 on 2026-07-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='Taille en octets', null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
